In [1]:
from __future__ import print_function
import torch


In [2]:
x = torch.empty(5,3)


In [3]:
print(x)
#UNINTIALIZED MATRIX

tensor([[-2.0383e-16,  6.2778e-43, -2.0383e-16],
        [ 6.2778e-43, -2.0383e-16,  6.2778e-43],
        [-2.0383e-16,  6.2778e-43, -2.0379e-16],
        [ 6.2778e-43, -2.0379e-16,  6.2778e-43],
        [-2.0379e-16,  6.2778e-43, -2.0379e-16]])


In [4]:
#RANDOMIZED MATRIX
x=torch.rand(5,3)
print(x)

tensor([[0.8968, 0.4670, 0.8033],
        [0.4299, 0.3046, 0.0041],
        [0.2520, 0.8879, 0.8081],
        [0.0903, 0.5791, 0.2929],
        [0.3822, 0.5914, 0.1326]])


In [5]:
#A MATRIX FILLED WITH ZEROS AND DTYPE LONG
x = torch.zeros(5,3, dtype= torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
#for filling values directly into matrix
x= torch.tensor([5.5, 3])

In [9]:
print(x)


tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5,3, dtype= torch.double)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
#operations
y = torch.rand(5, 3)
print(x + y)

tensor([[1.1868, 1.5070, 1.7972],
        [1.2315, 1.8493, 1.4461],
        [1.4230, 1.2287, 1.2091],
        [1.5963, 1.1159, 1.2049],
        [1.8872, 1.7472, 1.4399]], dtype=torch.float64)


In [12]:
print(torch.add(x,y))

tensor([[1.1868, 1.5070, 1.7972],
        [1.2315, 1.8493, 1.4461],
        [1.4230, 1.2287, 1.2091],
        [1.5963, 1.1159, 1.2049],
        [1.8872, 1.7472, 1.4399]], dtype=torch.float64)


In [13]:
#indexing
print(x[:,1])

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [15]:
#resizing
x= torch.randn(4,4)
y= x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
#CUDA TENSOR
if torch.cuda.is_available():
    device = torch.device("cuda")
    y=torch.ones_like(x, device = device )
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z=x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[ 0.5562, -0.2344,  0.7991,  0.9772],
        [ 0.0628,  2.3337,  1.9738,  2.2606],
        [ 1.1040,  1.2054, -2.1375,  1.1710],
        [ 4.6405,  0.3429,  0.7307,  1.6314]], device='cuda:0')
tensor([[ 0.5562, -0.2344,  0.7991,  0.9772],
        [ 0.0628,  2.3337,  1.9738,  2.2606],
        [ 1.1040,  1.2054, -2.1375,  1.1710],
        [ 4.6405,  0.3429,  0.7307,  1.6314]], dtype=torch.float64)
