In [1]:
#dependencies
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as f
from torch.utils.data import DataLoader,TensorDataset
from torch.optim import Adam

In [2]:
path='D:/Data Science/Machine Learning/Machine_Learning/Machine-Learning-A-Z-New/Machine Learning A-Z New\Part 2 - Regression/Section 5 - Multiple Linear Regression/'
df=pd.read_csv(path+'50_Startups.csv')

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
#segregating dependent and independent variables
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [5]:
#label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,3]=le.fit_transform(x[:,3])

In [6]:
x[:4]

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2]], dtype=object)

In [7]:
#printing shape
x.shape

(50, 4)

In [8]:
#converting to float
y=y.astype(dtype='float64')
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [10]:
x=x.astype(dtype='float64') #we had to convert the array to float because one col was int because it was encoded
x[:2]       #so we casted entire array as float array because tensors doesn't entertains heterogenous data types

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00]])

In [11]:
#two ways to convert arrays to tensors
x=torch.tensor(x) #first 
y=torch.from_numpy(y) #second
print(x[:2])
print(y[:2])

tensor([[1.6535e+05, 1.3690e+05, 4.7178e+05, 2.0000e+00],
        [1.6260e+05, 1.5138e+05, 4.4390e+05, 0.0000e+00]], dtype=torch.float64)
tensor([192261.8300, 191792.0600], dtype=torch.float64)


In [12]:
#definiing model
model=nn.Linear(x.shape[1],1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3399, -0.3651,  0.2471,  0.1764]], requires_grad=True)
Parameter containing:
tensor([0.3423], requires_grad=True)


In [13]:
#to view all the model parameters
print(model.parameters)
print(list(model.parameters()))

<bound method Module.parameters of Linear(in_features=4, out_features=1, bias=True)>
[Parameter containing:
tensor([[ 0.3399, -0.3651,  0.2471,  0.1764]], requires_grad=True), Parameter containing:
tensor([0.3423], requires_grad=True)]


In [14]:
y_pred=model(x.float())
print(y_pred)

tensor([[122803.3203],
        [109691.2344],
        [116030.2031],
        [100437.7734],
        [105418.1094],
        [ 98049.0938],
        [ 23576.8066],
        [ 71190.3594],
        [ 63680.3242],
        [ 77607.1953],
        [ 50891.9453],
        [ 62420.5547],
        [ 47159.7539],
        [ 44237.4922],
        [ 47003.1914],
        [ 58848.5352],
        [ 47446.0039],
        [ 49036.0469],
        [ 62378.9805],
        [-26668.2930],
        [ 58150.2109],
        [ 44573.4570],
        [ 55278.0391],
        [ 59657.4414],
        [ 24679.5312],
        [  5124.6401],
        [  6109.5776],
        [ 65103.3672],
        [-15031.2480],
        [ -7092.5811],
        [  1374.3323],
        [-13166.2441],
        [-14232.9648],
        [ 34276.7383],
        [ 10300.9092],
        [ 35376.6914],
        [ 13058.8359],
        [ 44944.0547],
        [ 28580.9863],
        [ 26055.1582],
        [  9195.4590],
        [ 19197.5742],
        [  9492.0967],
        [-3

In [15]:
#loss function
mse=f.mse_loss
loss=mse(y_pred.squeeze(1),y)
print(loss.double())

tensor(6.8772e+09, dtype=torch.float64, grad_fn=<MseLossBackward>)


In [16]:
#optimizer
opt=Adam(model.parameters(),lr=1e-2)

In [17]:
trainset=TensorDataset(x,y)
trainset[:2]

(tensor([[1.6535e+05, 1.3690e+05, 4.7178e+05, 2.0000e+00],
         [1.6260e+05, 1.5138e+05, 4.4390e+05, 0.0000e+00]], dtype=torch.float64),
 tensor([192261.8300, 191792.0600], dtype=torch.float64))

In [18]:
#loading the dataset
training_data=DataLoader(trainset,batch_size=5,shuffle=True)

In [19]:
for a,b in training_data:
    print(a)
    print(b)
    break

tensor([[6.4665e+04, 1.3955e+05, 1.3796e+05, 0.0000e+00],
        [1.6260e+05, 1.5138e+05, 4.4390e+05, 0.0000e+00],
        [1.2054e+05, 1.4872e+05, 3.1161e+05, 2.0000e+00],
        [1.1452e+05, 1.2262e+05, 2.6178e+05, 2.0000e+00],
        [5.5494e+04, 1.0306e+05, 2.1463e+05, 1.0000e+00]], dtype=torch.float64)
tensor([107404.3400, 191792.0600, 152211.7700, 129917.0400,  96778.9200],
       dtype=torch.float64)


In [ ]:
#training
epochs=100000
for epoch in range(epochs):
    for inputs,targets in training_data:
        pred=model(inputs.float())
        pred=pred.squeeze(1)
        #print(pred.shape)
        #print(inputs.dtype)
        #print(targets.dtype)
        #print(y_pred.dtype)
        pred=pred.double()
        loss=mse(pred,targets)
        loss.backward() #computing gradients
        opt.step() #updating parameters
        opt.zero_grad() #setting the grads back to zero
    if epoch%1000==0:
        print(f'Epoch:{epoch}/{epochs} | Loss:{loss.item()}')
        pass